# Saleor DEV Overlay: Replicas/Resources Patch
# DEV ?˜ê²½ ë¦¬ì†Œ???¤ì •

apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  namespace: kyeol
spec:
  replicas: 1  # DEV??1ê°?
  template:
    spec:
      containers:
        - name: storefront
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
