# Resources Patch - STAGE (DEVÎ≥¥Îã§ ?ÅÌñ•)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
spec:
  template:
    spec:
      containers:
        - name: storefront
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
