# Saleor Base: Storefront Horizontal Pod Autoscaler
# HPA v2 - CPU 및 Memory 기반 오토스케일링

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: storefront-hpa
  namespace: kyeol
  labels:
    app: storefront
    app.kubernetes.io/name: storefront
    app.kubernetes.io/part-of: saleor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storefront

  # 최소/최대 레플리카 수
  minReplicas: 2
  maxReplicas: 20  # 10 → 20 (Node 부족 상황 유발)

  # 메트릭 기준
  metrics:
    # CPU 사용률 기반 스케일링
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # 70% → 50% (더 빠른 트리거)

  # 스케일링 동작 설정
  behavior:
    # 스케일 업 정책 (Pod 증가)
    scaleUp:
      stabilizationWindowSeconds: 0  # 30초 → 0초 (즉시)
      policies:
        - type: Percent
          value: 200  # 100% → 200% (더 빠른 증가)
          periodSeconds: 10  # 15초 → 10초
        - type: Pods
          value: 5  # 2개 → 5개 (한 번에 더 많이)
          periodSeconds: 10
      selectPolicy: Max  # 위 정책 중 최대값 선택

    # 스케일 다운 정책 (Pod 감소)
    scaleDown:
      stabilizationWindowSeconds: 300  # 5분 안정화 기간 (급격한 감소 방지)
      policies:
        - type: Percent
          value: 50  # 현재 레플리카의 50%까지 한 번에 감소 가능
          periodSeconds: 60  # 60초마다 평가
        - type: Pods
          value: 1  # 또는 최대 1개 Pod까지 한 번에 감소
          periodSeconds: 60
      selectPolicy: Min  # 위 정책 중 최소값 선택 (보수적 감소)
