# ArgoCD Application: Saleor DEV

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saleor-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/MSP-Team3/kyeol-app-gitops.git
    targetRevision: main
    path: apps/saleor/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: kyeol-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
